"on":
  push:
    branches:
    - feroze
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Deploy stack
      timeout-minutes: 30
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: apply -f porter.yaml
      env:
        PORTER_CLUSTER: "2692"
        PORTER_HOST: https://dashboard.getporter.dev
        PORTER_PROJECT: "7151"
        PORTER_STACK_NAME: my-test-app
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_7151_2692 }}
